FROM python:3.7.4

# Set environment variables
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /

RUN pip install --upgrade pip
# Install dependencies.
RUN pip install -r /requirements.txt

# Set work directory.
RUN mkdir /code-app3
WORKDIR /code-app3

# Copy project code-app3.
COPY . /code-app3/

EXPOSE 9900
